### ISSUE TITLE
Teams Message Formatting

### ISSUE THREAD

**Issue by devan-cloud** [cloudandthings/terraform-aws-costnotifier#11]
Currently the emoticons attached to the message to the messengers only supports slack.
Teams gets a text translations.

![image](https://user-images.githubusercontent.com/108518315/197523544-567459c8-2c2d-432a-b357-27a68124caae.png)

**Comment by baolsen** [comment]
Related: #20

**Comment by baolsen** [comment]
Fixed in latest v2.0.0
