### ISSUE TITLE
feat(lambda): The lambda function should have a description and configurable timeout

### ISSUE THREAD

**Issue by baolsen** [cloudandthings/terraform-aws-costnotifier#19]
Two minor improvements:

- The lambda function should have a description where currently it is blank.
- The lambda timeout should be customisable, and set to a reduced value eg 2 minutes by default since the function normally runs in far less time.

**Comment by kayman-mk** [comment]
Is a configurable timeout really needed? The duration of the function should almost identically for all users, shouldn't it?

**Comment by baolsen** [comment]
@kayman-mk thanks for the feedback, agreed :)

Timeout should generally not be an issue as the lambda would complete quickly under normal conditions. 

So point 2 can be changed:

> The lambda timeout should be set to a reduced value eg 2 minutes since the function normally runs in far less time.
